name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - uses: docker/build-push-action@v5
      with:
            context: .
            platforms: linux/amd64,linux/arm64
            cache-from: type=gha
            cache-to: type=gha,mode=max
    
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version     #con esto tenemos acceso a todo el resultado del paso

    - name: Build Docker Image 
      uses: docker/build-push-action@v5
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pastrans/docker-grahql:${{ steps.version.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max


    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
